### PR TITLE
Fixed issues with the recovery for the Asus Zenfone 4 Selfie Pro

### PR DESCRIPTION
**Pull request by Frost1911**

### CODE REVIEW

**Comment by bigbiff** [comment]
Hello, please push this to the project at https://gerrit.twrp.me and add me for review.

**Comment by ghost** [comment]
> Hello, please push this to the project at https://gerrit.twrp.me and add me for review.

Thanks for your reply, but there is no Z01M repository on the gerrit.

**Comment by bigbiff** [comment]
The repository should now be available.

**Comment by Frost1911** [comment]
Hello, I was able to push the commits to Gerrit except the kernel (commit 8ae432a8df2cf675a8dfd10417842a16aa892d7e "Use latest stock kernel to fix touch/battery indicator issues") I got the following errors on the terminal: 
```
error: RPC failed; HTTP 413 curl 22 The requested URL returned error: 413
fatal: the remote end hung up unexpectedly
```

**Comment by bigbiff** [comment]
Are you using ssh as the remote? I think you might be using https because of the curl error. Https has issues with large files in git.

**Pull request closed without merging**
